version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: specmgr-redis
    ports:
      - "6400:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: specmgr-qdrant
    ports:
      - "6350:6333"
      - "6351:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application service (commented out for development)
  # app:
  #   build: .
  #   container_name: specmgr-app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - REDIS_URL=redis://redis:6379
  #     - QDRANT_URL=http://qdrant:6333
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     qdrant:
  #       condition: service_healthy

volumes:
  redis_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  default:
    name: specmgr-network